EMOJI_LIGAS = {
    "🇨🇴": ["liga betplay", "primera a", "primera b"],
    "🇦🇷": ["liga profesional", "superliga argentina", "copa argentina"],
    "🇲🇽": ["liga mx", "liga mexicana", "copa mx"],
    "🇺🇸": ["mls", "major league soccer", "us open cup"],
    "🇳🇱": ["eredivisie", "knvb beker"],
    "🇵🇹": ["primeira liga", "taça de portugal", "taça da liga"],
    "🇹🇷": ["süper lig", "turkish cup"],
    "🇷🇺": ["russian premier league", "russian cup"],
    "🇧🇪": ["jupiler pro league", "belgian cup"],
    "🇩🇪": ["bundesliga"],
    "🇫🇷": ["ligue 1"],
    "🇬🇧": ["premier league", "championship", "fa cup", "carabao cup"],
    "🇪🇸": ["la liga", "copa del rey", "supercopa de españa"],
    "🇧🇷": ["campeonato brasileño serie a", "serie b", "copa do brasil"],
    "🇮🇹": ["serie a", "coppa italia"],
    "🏆": ["champions league", "uefa champions league", "libertadores", "copa libertadores", "copa america", "eurocopa"],
    "🥈": ["europa league", "uefa europa league"],
    "🥉": ["sudamericana", "copa sudamericana", "conference league", "uefa conference league"],
    "🌍": ["mundial", "world cup", "copa mundial", "eurocopa", "european championship", "copa america", "africa cup of nations", "asia cup", "eliminatorias"]
}

# Mapa de nombres de paises (espanol e ingles) a banderas
# Usado por Partido._agregar_banderas() para decorar los equipos
BANDERAS = {
    "espana": "🇪🇸", "spain": "🇪🇸",
    "belgica": "🇧🇪", "belgium": "🇧🇪",
    "argentina": "🇦🇷",
    "brasil": "🇧🇷", "brazil": "🇧🇷",
    "francia": "🇫🇷", "france": "🇫🇷",
    "alemania": "🇩🇪", "germany": "🇩🇪",
    "italia": "🇮🇹", "italy": "🇮🇹",
    "portugal": "🇵🇹",
    "holanda": "🇳🇱", "netherlands": "🇳🇱", "paises bajos": "🇳🇱",
    "inglaterra": "🏴󠁧󠁢󠁥󠁮󠁧󠁿", "england": "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
    "colombia": "🇨🇴",
    "uruguay": "🇺🇾",
    "mexico": "🇲🇽", "mexic": "🇲🇽",
    "chile": "🇨🇱",
    "peru": "🇵🇪", "perú": "🇵🇪",
    "ecuador": "🇪🇨",
    "paraguay": "🇵🇾",
    "bolivia": "🇧🇴",
    "venezuela": "🇻🇪",
    "eeuu": "🇺🇸", "estados unidos": "🇺🇸", "usa": "🇺🇸", "united states": "🇺🇸",
    "canada": "🇨🇦", "canadá": "🇨🇦",
    "costa rica": "🇨🇷",
    "japon": "🇯🇵", "japan": "🇯🇵", "japón": "🇯🇵",
    "corea": "🇰🇷", "korea": "🇰🇷", "sur corea": "🇰🇷", "south korea": "🇰🇷",
    "arabia saudita": "🇸🇦", "saudi arabia": "🇸🇦",
    "australia": "🇦🇺",
    "nigeria": "🇳🇬",
    "camerun": "🇨🇲", "cameroon": "🇨🇲", "camarún": "🇨🇲",
    "senegal": "🇸🇳",
    "ghana": "🇬🇭",
    "costa de marfil": "🇨🇮", "ivory coast": "🇨🇮",
    "marruecos": "🇲🇦", "morocco": "🇲🇦",
    "tunez": "🇹🇳", "tunisia": "🇹🇳",
    "egipto": "🇪🇬", "egypt": "🇪🇬",
    "argelia": "🇩🇿", "algeria": "🇩🇿",
    "sudafrica": "🇿🇦", "south africa": "🇿🇦",
    "rusia": "🇷🇺", "russia": "🇷🇺",
    "croacia": "🇭🇷", "croatia": "🇭🇷",
    "suiza": "🇨🇭", "switzerland": "🇨🇭",
    "dinamarca": "🇩🇰", "denmark": "🇩🇰",
    "suecia": "🇸🇪", "sweden": "🇸🇪",
    "noruega": "🇳🇴", "norway": "🇳🇴",
    "polonia": "🇵🇱", "poland": "🇵🇱",
    "republica checa": "🇨🇿", "czech republic": "🇨🇿",
    "austria": "🇦🇹",
    "hungria": "🇭🇺", "hungary": "🇭🇺",
    "serbia": "🇷🇸",
    "turquia": "🇹🇷", "turkey": "🇹🇷",
    "grecia": "🇬🇷", "greece": "🇬🇷",
    "ucrania": "🇺🇦", "ukraine": "🇺🇦",
    "gales": "🏴󠁧󠁢󠁷󠁬󠁳󠁿", "wales": "🏴󠁧󠁢󠁷󠁬󠁳󠁿",
    "escocia": "🏴󠁧󠁢󠁳󠁣󠁴󠁿", "scotland": "🏴󠁧󠁢󠁳󠁣󠁴󠁿",
    "irlanda": "🇮🇪", "ireland": "🇮🇪",
    "paises bajos": "🇳🇱",
    "ucrania": "🇺🇦",
    "eslovaquia": "🇸🇰", "slovakia": "🇸🇰",
    "eslovenia": "🇸🇮", "slovenia": "🇸🇮",
    "rumania": "🇷🇴", "romania": "🇷🇴",
    "bulgaria": "🇧🇬", "bulgaria": "🇧🇬",
    "montenegro": "🇲🇪",
    "bosnia": "🇧🇦", "bosnia and herzegovina": "🇧🇦",
    "macedonia": "🇲🇰", "north macedonia": "🇲🇰",
    "albania": "🇦🇱",
    "islandia": "🇮🇸", "iceland": "🇮🇸",
    "finlandia": "🇫🇮", "finland": "🇫🇮",
    "letonia": "🇱🇻", "latvia": "🇱🇻",
    "lituania": "🇱🇹", "lithuania": "🇱🇹",
    "estonia": "🇪🇪", "estonia": "🇪🇪",
    "chipre": "🇨🇾", "cyprus": "🇨🇾",
    "israel": "🇮🇱",
    "iran": "🇮🇷",
    "irak": "🇮🇶", "iraq": "🇮🇶",
    "catar": "🇶🇦", "qatar": "🇶🇦",
    "emiratos arabes": "🇦🇪", "uae": "🇦🇪", "united arab emirates": "🇦🇪",
    "jordania": "🇯🇴", "jordan": "🇯🇴",
    "china": "🇨🇳",
    "india": "🇮🇳",
    "indonesia": "🇮🇩",
    "tailandia": "🇹🇭", "thailand": "🇹🇭",
    "nueva zelanda": "🇳🇿", "new zealand": "🇳🇿",
    "honduras": "🇭🇳",
    "guatemala": "🇬🇹",
    "el salvador": "🇸🇻",
    "panama": "🇵🇦", "panamá": "🇵🇦",
    "haiti": "🇭🇹", "haití": "🇭🇹",
    "jamaica": "🇯🇲",
    "trinidad y tobago": "🇹🇹",
    "cuba": "🇨🇺",
    "republica dominicana": "🇩🇴", "dominican republic": "🇩🇴",
}