EMOJI_LIGAS = {
    "🇨🇴": ["liga betplay", "primera a", "primera b"],
    "🇦🇷": ["liga profesional", "superliga argentina", "copa argentina"],
    "🇲🇽": ["liga mx", "liga mexicana", "copa mx"],
    "🇺🇸": ["mls", "major league soccer", "us open cup"],
    "🇳🇱": ["eredivisie", "knvb beker"],
    "🇵🇹": ["primeira liga", "taça de portugal", "taça da liga"],
    "🇹🇷": ["süper lig", "turkish cup"],
    "🇷🇺": ["russian premier league", "russian cup"],
    "🇧🇪": ["jupiler pro league", "belgian cup"],
    "🇩🇪": ["bundesliga"],
    "🇫🇷": ["ligue 1"],
    "🇬🇧": ["premier league", "championship", "fa cup", "carabao cup"],
    "🇪🇸": ["la liga", "copa del rey", "supercopa de españa"],
    "🇧🇷": ["campeonato brasileño serie a", "serie b", "copa do brasil"],
    "🇮🇹": ["serie a", "coppa italia"],
    "🏆": ["champions league", "uefa champions league", "libertadores", "copa libertadores", "copa america", "eurocopa"],
    "🥈": ["europa league", "uefa europa league"],
    "🥉": ["sudamericana", "copa sudamericana", "conference league", "uefa conference league"],
    "🌍": ["mundial", "world cup", "copa mundial", "eurocopa", "european championship", "copa america", "africa cup of nations", "asia cup", "eliminatorias"]
}